### ISSUE TITLE
Debug mode crash 

### ISSUE THREAD

**Issue by FreezeDriedMangos** [xen-42/outer-wilds-new-horizons#104]
### What Happened?

Doing the raycast position check while looking at your scout crashes the game.

I found this bug while in the stranger’s star viewing room on the dam, with my scout on the floor next to a chair.

### Platform

Steam

### Mods

```Markdown
Outer Wilds Mod Manager
OWML
PacificEngine's Common Resources
New Horizons
Ship Log Slide Reel Player
Unity Explorer
```

**Comment by xen-42** [comment]
I'm unable to recreate this so I can't fix it. I point at my scout and it just works normally and ignores the scout's collision.

**Comment by xen-42** [comment]
Seems to be fixed
