### ISSUE TITLE
procGen in AsteroidBelt module does nothing

### ISSUE THREAD

**Issue by TerrificTrifid** [xen-42/outer-wilds-new-horizons#120]
### What Happened?

It has no effect on the asteroids. Should probably just be replaced with a color setting since minSize/maxSize makes procGen scale pointless.

### Platform

Steam

### Mods

```Markdown
NH
```

**Comment by xen-42** [comment]
Fixed, leaving proc gen on asteroids because the idea is to actually add more features to proc gen in the future like materials and stuff
