### ISSUE TITLE
Where to put the folder with the planets?

### ISSUE THREAD

**Issue by OuterWilds** [xen-42/outer-wilds-new-horizons#14]
Thanks for the mod.
I have a slightly stupid question, maybe it's written somewhere but I just didn't notice. I didn't quite understand where to drop the planets folder so that everything would work.

**Comment by OuterWilds** [comment]
I also want to know about creating my own planets. You have pointed out a way to add props to a planet, but is it possible to add a 3D model of a planet in the same way?

**Comment by xen-42** [comment]
The planets folder goes in OuterWildsModManager/OWML/Mods/xen.NewHorizons (where the mod is installed), by default that's in roaming appdata. You can add a 3d model of a planet the same way as general props, just make it a rly big prop at position 0, 0, 0.

**Comment by OuterWilds** [comment]
Thanks a lot for your answer!
