### ISSUE TITLE
Orbit Lines have no material

### ISSUE THREAD

**Issue by MegaPiggy** [xen-42/outer-wilds-new-horizons#141]
### What Happened?

I edited the RSS config to start in that system. Then I fly to my custom system and the orbit lines are broken.
[Upsilon Andromedae](https://drive.google.com/file/d/1ucRWtz_G-HKZ2CIHD_LC1OfB602NcNnH/view?usp=sharing)

It can't find the "OrbitLine_CO" object in Interloper because it is somehow inactive.

https://user-images.githubusercontent.com/34462599/169201167-d43f5943-158e-41e8-bdd9-713f122f5041.mp4

https://user-images.githubusercontent.com/34462599/169201302-01b6b521-746d-417a-be54-e703d86d3f51.mp4

### What was supposed to happen?

Orbit Lines should have a material

### Platform

Epic Games

### Mods

```Markdown
Real Solar System
Upsilon Andromedae
PacificEngine's Common Resources
Cheats Mod
Unity Explorer
Run In Background
```

### Logs

```Shell
NullReferenceException: Object reference not set to an instance of an object
Stacktrace: NewHorizons.Builder.Orbital.OrbitlineBuilder.Make (UnityEngine.GameObject planetGO, NewHorizons.Components.Orbital.NHAstroObject astroObject, System.Boolean isMoon, NewHorizons.External.Configs.IPlanetConfig config) (at <932216d184e147e5bd8fb586fd58992a>:0)
NewHorizons.Handlers.PlanetCreationHandler+<>c__DisplayClass6_0.<GenerateBody>b__0 () (at <932216d184e147e5bd8fb586fd58992a>:0)
OWML.ModHelper.Events.ModUnityEvents+<WaitForFrames>d__12.MoveNext () (at <b9f0b575bc57466aa5cda12f43639cfb>:0)
UnityEngine.SetupCoroutine.InvokeMoveNext (System.Collections.IEnumerator enumerator, System.IntPtr returnValueAddress) (at <469e86e97fa2467ebffe49bbd6086325>:0)
```

**Comment by xen-42** [comment]
If we only use the comet to get its line renderer and steal the material, we could instead just load that material directly from its name. Shouldn't be too much to fix. Bizarre that its inactive though, I blame CR.
