### ISSUE TITLE
Better tornado audio distances

### ISSUE THREAD

**Issue by TerrificTrifid** [xen-42/outer-wilds-new-horizons#178]
### Feature

Currently AudioSource.maxDistance is coupled to height*10, which is way too high, and minDistance is always 50. A better method would be coupling maxDistance to just height, and minDistance to height/10. This would make it scale basically the same as Giant's Deep. A custom maxDistance option would also be nice.

**Comment by xen-42** [comment]
Oh damn yeah, that's leftover from when the tornados were based on the GD ones (100 height) and not the BH ones (10 height) so I was still using a factor of 100 not 10. Good catch.
