### ISSUE TITLE
Warping seems to break completely in NomaiVR

### ISSUE THREAD

**Issue by SpencerMeow** [xen-42/outer-wilds-new-horizons#18]
I was trying to use 2 mods (seperately) in NomaiVR today, Outer Wilds Galaxy, and Gargantua/Interstellar, but when I enter any warp it just is stuck on black and all I can hear is the purple gravity elevator noise on loop, and the headset latency goes crazy high.

**Comment by xen-42** [comment]
Can you share the logs from the mod manager please

**Comment by SpencerMeow** [comment]
> 

Hey I'm really sorry for the late response,  here is the logs
[OWML.Log.24-01-2022-20.16.47.txt](https://github.com/xen-42/outer-wilds-new-horizons/files/7930135/OWML.Log.24-01-2022-20.16.47.txt)

**Comment by xen-42** [comment]
This should be fixed by now (assuming this was caused by the dreaded warp bug)
