### ISSUE TITLE
Achievements+

### ISSUE THREAD

**Issue by xen-42** [xen-42/outer-wilds-new-horizons#197]
### Feature

Achievements triggered by volumes, ship log facts, and dialogue conditions. Requested by Trifid.

### Context

Repurpose the current fact reveal stuff to have an option to either reveal a fact, unlock an achievement, or set a condition.

For ship log facts and dialogue conditions, we'll need a mod config file where we'll set those.

**Comment by Bwc9876** [comment]
Done in #199
