### ISSUE TITLE
Orbits around focal points are broken

### ISSUE THREAD

**Issue by MegaPiggy** [xen-42/outer-wilds-new-horizons#221]
### What Happened?

Anything that used to orbit a focal point now seems to just float away from the focal point instead.
![image](https://user-images.githubusercontent.com/34462599/177376067-b416d97a-19b9-48eb-ad57-b8b7a5708bee.png)

### What was supposed to happen?

They are supposed to orbit normally instead.

### Mods

```Markdown
Real Solar System
```

### Logs

```Shell
No errors
```

**Comment by xen-42** [comment]
Fake barycenter should be removed and its gravity stuff applied to the real focalpoint. This would just avoid this issue entirely.
