### ISSUE TITLE
Orbit line renderer tweak

### ISSUE THREAD

**Issue by TerrificTrifid** [xen-42/outer-wilds-new-horizons#227]
### Feature

LineRenderer.endColor should be tint with 0 alpha, instead of white with 0 alpha. This will make the lines retain their color as they fade out, which looks prettier and is what base game does.

**Comment by xen-42** [comment]
Implemented in https://github.com/xen-42/outer-wilds-new-horizons/commit/c7c781e2cdd936795582fc9ca0291652d9c296a3
