### ISSUE TITLE
Mp4 format for slides

### ISSUE THREAD

**Issue by hearth1an** [xen-42/outer-wilds-new-horizons#230]
### Feature

Mp4 format for slides (with audio). It took very long time to make all slides and then synchronize them with audiofile.

**Comment by xen-42** [comment]
Done in 1.4.0

**Comment by xen-42** [comment]
I misread this as mp3

**Comment by xen-42** [comment]
This goes beyond the scope of slides in the base game and as such won't be implemented.

**Comment by JohnCorby** [comment]
sorry
