### ISSUE TITLE
Higher resolution heightmaps cause a massive seam on planets.

### ISSUE THREAD

**Issue by mrwallace888** [xen-42/outer-wilds-new-horizons#234]
### What Happened?

When forcing NH to generate planets with a higher resolution heightmap instead of the default 256x128, a nasty seam appears on planets. This seam gets bigger the bigger the heightmap resolution is.
![image](https://user-images.githubusercontent.com/39398330/179035538-8a5ca9d1-fcba-4d74-b774-1a515da3b71f.png)

### What was supposed to happen?

Unsure. Probably not cause a seam.

### Platform

Steam

**Comment by mrwallace888** [comment]
To add to the problem it's not part of the heightmap texture. I have a planet heightmap where the oceans are pure black to be the furthest back they can be height-wise. Regardless, I see a blue spike sticking out of the ocean that goes all the way around.
![image](https://user-images.githubusercontent.com/39398330/179035327-00191315-02e0-481c-b050-d860285114d1.png)

**Comment by mrwallace888** [comment]
Turns out it's not where the ends of the texture meet. It does a full straight-line 360 across the globe from north to south. One point of the line is beside that little smiley face on the top next to the ocean on the right and the ocean wall thing I mentioned goes across that star-shaped lake on the bottom left there.

**Comment by xen-42** [comment]
Fixed in https://github.com/xen-42/outer-wilds-new-horizons/commit/38ac50652b798b60c81b86cc7c541ab10e9374c8 will be included in 1.4.0 or 1.4.1
