### ISSUE TITLE
Shades of gray aren't gray

### ISSUE THREAD

**Issue by TerrificTrifid** [xen-42/outer-wilds-new-horizons#27]
At least for planet/cloud textures, any shade of gray, ranging from white to black, is instead tinted tan-ish. I think it's intended for the Attlerock, but everywhere else, it's just annoying and weird. Especially since there's also a cutoff in darkness, causing black colors to appear the same as gray.

**Comment by xen-42** [comment]
Shaders imported from Asset Bundles are broken for some reason, this happens in a number of mods. Will have to ask like Logan or smthng

**Comment by Bwc9876** [comment]
Change color space to `linear` in the unity project
- [ ] Mention on docs probably
- [ ] Implement on unity template
- [ ] Change the nh bundle to use linear
*ty JohnCorby*
