### ISSUE TITLE
Can't create new expeditions and continue already existing one, take any damage and signalscope not seeing any signals

### ISSUE THREAD

**Issue by GinDoyr** [xen-42/outer-wilds-new-horizons#276]
### What Happened?

Title says it all. Tried to play with this mod installed and got some funny stuff happening. All of this is happening when this mod is activated, with or without any other mods. Downloading the game, mod loader again and deleting all of their files in AppData didn't help too. Can't attach a video so I kinda have to attach a link instead, sorry :(  https://youtu.be/8z35auf9xy4 (ik it's laggy and all, sorry for that)

### Platform

Steam

### Mods

```Markdown
Played with these mods before downloading the mod:
PacificEngine's Common Resources - 0.5.14
Menu Framework (was disabled) - 3.0.0
Clock - 0.7.0
Cheats Mod - 0.7.4
Unity Explorer (was disabled) - 4.9.0
TimeSaver - 0.2.0
```

### Logs
(hope it's smth useful)
<html>
<body>

NullReferenceException: Object reference not set to an instance of an objectStacktrace: NewHorizons.NewHorizonsApi.LoadConfigs (OWML.Common.IModBehaviour mod) (at <434b9f9f496d4de2b69cb3577574ba61>:0)OWMLInteraction.Proxies.From<xen.NewHorizonsExamples_NewHorizonsTemplate.INewHorizons>_To<xen.NewHorizons_NewHorizons.NewHorizonsApi>.LoadConfigs (OWML.Common.IModBehaviour ) (at <5821474a78dc4130b06b03bcf4827a4a>:0)NewHorizonsTemplate.NewHorizonsTemplate.Start () (at <ba99ffa938874da1bb94500a1d347533>:0) | OWML |  
NullReferenceException: Object reference not set to an instance of an objectStacktrace: NewHorizons.Utility.Logger.Log (System.String text, NewHorizons.Utility.Logger+LogType type) (at <434b9f9f496d4de2b69cb3577574ba61>:0)NewHorizons.Utility.Logger.LogError (System.String text) (at <434b9f9f496d4de2b69cb3577574ba61>:0)NewHorizons.External.NewHorizonsData.Load () (at <434b9f9f496d4de2b69cb3577574ba61>:0)NewHorizons.External.NewHorizonsData.Reset () (at <434b9f9f496d4de2b69cb3577574ba61>:0)NewHorizons.Patches.PlayerDataPatches.OnPlayerDataResetGame () (at <434b9f9f496d4de2b69cb3577574ba61>:0)(wrapper dynamic-method) PlayerData.DMD<PlayerData::ResetGame>()TitleScreenManager.OnNewGameSubmit () (at <1969d6105fed4946a9cb041234d375bc>:0)SubmitAction.Submit () (at <1969d6105fed4946a9cb041234d375bc>:0)SubmitActionConfirm.ConfirmSubmit () (at <1969d6105fed4946a9cb041234d375bc>:0)SubmitActionLoadScene.ConfirmSubmit () (at <1969d6105fed4946a9cb041234d375bc>:0)SubmitActionConfirm.Submit () (at <1969d6105fed4946a9cb041234d375bc>:0)SubmitAction.OnPointerClick (UnityEngine.EventSystems.PointerEventData pointerEventData) (at <1969d6105fed4946a9cb041234d375bc>:0)UnityEngine.EventSystems.ExecuteEvents.Execute (UnityEngine.EventSystems.IPointerClickHandler handler, UnityEngine.EventSystems.BaseEventData eventData) (at <5662eb13bed3429984af50398b0e65f3>:0)UnityEngine.EventSystems.ExecuteEvents.Execute[T] (UnityEngine.GameObject target, UnityEngine.EventSystems.BaseEventData eventData, UnityEngine.EventSystems.ExecuteEvents+EventFunction`1[T1] functor) (at <5662eb13bed3429984af50398b0e65f3>:0)UnityEngine.EventSystems.ExecuteEvents:Execute(GameObject, BaseEventData, EventFunction`1)OWMenuInputModule:ProcessPointerButton(ButtonState&, PointerEventData)OWMenuInputModule:ProcessPointer(PointerModelExposed&)OWMenuInputModule:ProcessMouseEvent()OWMenuInputModule:Process()UnityEngine.EventSystems.EventSystem:Update() | OWML |  
NullReferenceException: Object reference not set to an instance of an objectStacktrace: NewHorizons.External.NewHorizonsData.Save () (at <434b9f9f496d4de2b69cb3577574ba61>:0)NewHorizons.External.NewHorizonsData.Reset () (at <434b9f9f496d4de2b69cb3577574ba61>:0)NewHorizons.Patches.PlayerDataPatches.OnPlayerDataResetGame () (at <434b9f9f496d4de2b69cb3577574ba61>:0)(wrapper dynamic-method) PlayerData.DMD<PlayerData::ResetGame>()TitleScreenManager.OnNewGameSubmit () (at <1969d6105fed4946a9cb041234d375bc>:0)SubmitAction.Submit () (at <1969d6105fed4946a9cb041234d375bc>:0)SubmitActionConfirm.ConfirmSubmit () (at <1969d6105fed4946a9cb041234d375bc>:0)SubmitActionLoadScene.ConfirmSubmit () (at <1969d6105fed4946a9cb041234d375bc>:0)SubmitActionConfirm.Submit () (at <1969d6105fed4946a9cb041234d375bc>:0)SubmitAction.OnPointerClick (UnityEngine.EventSystems.PointerEventData pointerEventData) (at <1969d6105fed4946a9cb041234d375bc>:0)UnityEngine.EventSystems.ExecuteEvents.Execute (UnityEngine.EventSystems.IPointerClickHandler handler, UnityEngine.EventSystems.BaseEventData eventData) (at <5662eb13bed3429984af50398b0e65f3>:0)UnityEngine.EventSystems.ExecuteEvents.Execute[T] (UnityEngine.GameObject target, UnityEngine.EventSystems.BaseEventData eventData, UnityEngine.EventSystems.ExecuteEvents+EventFunction`1[T1] functor) (at <5662eb13bed3429984af50398b0e65f3>:0)UnityEngine.EventSystems.ExecuteEvents:Execute(GameObject, BaseEventData, EventFunction`1)OWMenuInputModule:ProcessPointerButton(ButtonState&, PointerEventData)OWMenuInputModule:ProcessPointer(PointerModelExposed&)OWMenuInputModule:ProcessMouseEvent()OWMenuInputModule:Process()UnityEngine.EventSystems.EventSystem:Update() | OWML | 8
 

<br class="Apple-interchange-newline">
</body>
</html>

**Comment by xen-42** [comment]
You have to update to the latest version of the game, you're on 1.1.10 and have to be on 1.1.12

**Comment by xen-42** [comment]
Also thank you for making the most detailed bug report ever very cool made it really easy to see the issue ty

**Comment by GinDoyr** [comment]
oh aaaa you're welcome, glad to hear that :)
