### ISSUE TITLE
Ring sounds

### ISSUE THREAD

**Issue by TerrificTrifid** [xen-42/outer-wilds-new-horizons#30]
Add config under ring module for soundType: Normal (hourglass funnel sound), Accretion (violent reentry sound), or default None.

**Comment by xen-42** [comment]
Implemented in https://github.com/xen-42/outer-wilds-new-horizons/commit/2460bbafb76eb88b73ccf2140c4c15ad106899aa rings can either be CLOUD, WATER, SAND, PLASMA, or NONE.
