### ISSUE TITLE
Improve docs

### ISSUE THREAD

**Issue by xen-42** [xen-42/outer-wilds-new-horizons#69]
- [x] Write dialogue guide on the dialogue page
- [x] Provide a detailing example on the details page
- [x] Link to the relevant schema things from dialogue and detailing pages
- [x] Rename body schema to celestial body fr
- [x] Explicitly write how to make a planet's surface with a model on the detailing page
- [x] Recolor Accordions to be less confusing
- [x] Add Patreon link on homepage
- [x] Add link to world upload tool on homepage
- [x] Mention VSCode on homepage
- [x] Explain what a schema is on homepage
- [x] Fix all the defaults in the schemas
- [x] Explain log level and debug mode config options
- [x] Add `GetInstalledAddons` to interface code snippet

**Comment by Bwc9876** [comment]
Joe mama
