### ISSUE TITLE
Ambient Occlusion disappears in close range

### ISSUE THREAD

**Issue by Nolram12345** [xen-42/outer-wilds-new-horizons#70]
**Describe the bug**
When New Horizons is enabled, Ambient Occlusion disappears in the close range.

**To Reproduce**
1. Enable New Horizons
2. Start the game
3. Observe the ambient occlusion while walking back and forth

**Expected behavior**
Ambient Occlusion should be there. 

**Screenshots**
Here is a video of the problem : 

https://user-images.githubusercontent.com/37701550/158260323-8ecc10b9-7130-45ef-b0a2-9ade62b0df06.mp4

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Firefox
 - Version: idk

**Smartphone (please complete the following information):**
 - Device: iPhone 6
 - OS:
 - Browser: Xen you should customize this template
 - Version: 0

**Additional context**
idk man

**Comment by Ciborgm9** [comment]
Hey! that happens to me!

**Comment by Ciborgm9** [comment]
Oh wait it is diffent thing

**Comment by xen-42** [comment]
Fixed in [v0.17.0](https://github.com/xen-42/outer-wilds-new-horizons/tree/v0.17.0)
