### ISSUE TITLE
Add the ability to edit existing dialogue

### ISSUE THREAD

**Issue by Bwc9876** [xen-42/outer-wilds-new-horizons#83]
Add the ability to edit and append to existing dialogue trees

Any nodes with new names will be added

Any nodes with names that are already in the tree will override the existing node with that name

**Comment by xen-42** [comment]
Instead just add a parameter where you add the path to whatever game object has the component that makes them look at you. Then make them look at you when you do that dialogue. If you wanna replace a dialogue, add your new dialogue where it was and delete the old one.
