### ISSUE TITLE
While R, G, and B work for coloring clouds, Alpha doesn't

### ISSUE THREAD

**Issue by CrypticBird** [xen-42/outer-wilds-new-horizons#90]
I know NH was recently updated to account for RGB values in cloud coloration (previously, clouds were just red no matter what). However, the alpha value seems to not be fixed. For example, if you were to set R to 19, G to 192, and B to 130, you will always get the exact same result, regardless of if alpha is 1, 100, 225 or anything in between. 🤓 Bro Idiot added that nerd face, not me okay??

**Comment by xen-42** [comment]
uh yeah clouds dont work with transparency maybe idk

**Comment by CrypticBird** [comment]
Does that mean there's no way to make white clouds? Or is there some other way to do it?

**Comment by xen-42** [comment]
how would alpha affect clouds, they must be opaque.
